# Generated by Django 3.0.3 on 2020-05-31 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_img', models.ImageField(blank=True, null=True, upload_to='media')),
                ('slider_text', models.TextField()),
                ('slider_title', models.CharField(max_length=120)),
            ],
        ),
    ]
